{% set name = "connexion" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/connexion-{{ version }}.tar.gz
  sha256: 0715d4a0393437aa2a48c144756360f9b5292635a05fd15c38cbbaf04ef5acb9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # inflection >=0.3.1 and <0.6 is not present on s390x
  skip: True  # [py<38 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
    - poetry-core >=1.2.0
  run:
    - python
    - asgiref >=3.4
    - httpx >=0.23
    - inflection >=0.3.1
    - jsonschema >=4.17.3
    - Jinja2 >=3.0.0
    - python-multipart >=0.0.15
    - PyYAML >=5.1
    - requests >=2.27
    - starlette >=0.35
    - typing-extensions >=4.6.1
    - werkzeug >=2.2.1

test:
  requires:
    - pip
  imports:
    - connexion
    - connexion.apps
    - connexion.decorators
    - connexion.middleware
    - connexion.operations
    - connexion.resources
    - connexion.validators
  commands:
    - connexion --version
    - pip check

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support
  description: Connexion is a modern Python web framework that makes spec-first and api-first development easy.
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
    - xylar
