{% set version = "2.8.0" %}

package:
  name: connexion
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/zalando/connexion/archive/{{ version }}.tar.gz
  sha256: ec8d429b1a677762158094b169414e9e48dd952db4330cd1583092e25f2e2770

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - connexion = connexion.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - flake8
    - setuptools
    - wheel

  run:
    - python >=3.6
    - clickclick >=1.2,<21
    - jsonschema >=2.5.1,<4
    - pyyaml >=5.1,<6
    - requests >=2.9.1,<3
    - inflection >=0.3.1,<0.6
    - flask >=1.0.4,<2
    - openapi-spec-validator >=0.2.4,<0.4
    - swagger-ui-bundle >=0.0.2,<0.1
    - aiohttp >=2.3.10,<4
    - aiohttp-jinja2 >=0.14.0,<2

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators
    - connexion.operations
    - connexion.security
  requires:
    - pip
  commands:
    - pip check
    - connexion --version

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: 'Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
