{% set version = "2.3.0" %}

package:
  name: connexion
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/zalando/connexion/archive/{{ version }}.tar.gz
  sha256: dbb8ab5627e75ec0764fcab1cbf2c7c8d463e8ab5dc855aa2a4ec396e89f83bd

build:
  number: 0
  noarch: python
  script: pip install --no-deps -vv .
  entry_points:
    - connexion = connexion.cli:main

requirements:
  host:
    - python >=3
    - pip
    - flake8

  run:
    - python >=3
    - clickclick >=1.2
    - jsonschema >=2.5.1
    - pyyaml >=5.1
    - requests >=2.9.1
    - six >=1.9
    - inflection >=0.3.1
    - flask >=1.0.4
    - openapi-spec-validator >=0.2.4

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators

  commands:
    - connexion --version

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: 'Swagger/OpenAPI First framework for Python on top of Flask with automatic endpoint validation & OAuth2 support'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
