{% set version = "1.4.2" %}

package:
  name: connexion
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/zalando/connexion/archive/{{ version }}.tar.gz
  sha256: f3aa674ca2675383c3382a60735078cce21795ef5571921d4b9590bfde6b753b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - connexion = connexion.cli:main

requirements:
  build:
    - python
    - setuptools
    - flake8

  run:
    - python
    - clickclick >=1.2
    - jsonschema >=2.5.1
    - pyyaml >=3.11
    - requests >=2.9.1
    - six >=1.9
    - swagger-spec-validator >=2.0.2
    - inflection >=0.3.1
    - typing >=3.6.1
    - flask >=0.10.1
    - pathlib >=1.0.1  # [py27]

test:
  imports:
    - connexion
    - connexion.apis
    - connexion.apps
    - connexion.decorators

  commands:
    - connexion --version

about:
  home: https://github.com/zalando/connexion
  license: Apache-2.0
  summary: 'Connexion - API first applications with OpenAPI/Swagger and Flask'
  license_family: APACHE
  license_file: LICENSE.txt
  dev_url: https://github.com/zalando/connexion
  doc_url: https://connexion.readthedocs.io/

extra:
  recipe-maintainers:
    - rvalieris
