travis:
  secure:
    BINSTAR_TOKEN: DxW5mAZlbCp3Q4ppIzKOStJN145LHuoICujffq2Tu/p8g68XXKKsMjfWhWlELiC6P8MWMmjYZBAxkiM+rgA1NKOjNxkj9k7bnvZSa7SoJ8Cob3/kBgGjrqYlhcnzA/ZIMLWPdjveEh6kiZBvZa4xabPtj41rbLq69QLH2XVlY+ByB6qW7yLBko1ZSJXtZM4COllLurB2rr20eFpZwtZdGv6kbiqViKG3JYG/xwtCiSab6cI89maOFc/PemCcQZ40bvU0Dp0HhigEeBlXVNrEAV7rdUVcaZ7N6fucEUQhiXd9/pZOe548QE9VQoBiyZnTStU9DEEfOP5Y5YcdPenv+5/hM0W1T/AXucqkGH65gKotdlnrB+udqREV5K+URiJ+W176h8V5ws6gLAYJcQHsMAejoOkJLU5JeqB/2+D+LaLDGLNehEYSIkxD9+b5eJc0y7kzhMNbWKCVR85diOTptMoqLMmRb6Mb0sTgrFt5tfp8GogASIIZxnRjp+rO3tNWsgMQtGQ3MEuntHn/er6ZYRuG44eUN1F1k5v3ITR4IS+medvfozwawx2CgRyBYDrHQtxjbgawDiitU5UfWc5Lim3PU4EboejMIna69fRQqvRJElujWwnVbogR6QW8lmaNeKM2ezZuWc12btbOu+kwYaE4t9pl3Xi+WBt40PIcrBs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
